ARG BUILDER=docker.io/oven/bun:alpine
FROM $BUILDER

RUN mkdir /app
WORKDIR /app

COPY --chown=0:0 extra-certs.pem /etc/
RUN sh -c '[ -s /etc/extra-certs.pem ] && cat /etc/extra-certs.pem >> /etc/ssl/certs/ca-certificates.crt || true'

RUN apk add --no-cache ca-certificates curl coreutils

RUN sh -c '[ -s /etc/extra-certs.pem ] && csplit -s -z -f "/usr/local/share/ca-certificates/extra-cert-" -b "%02d.crt" /etc/extra-certs.pem "/-----BEGIN CERTIFICATE-----/" "{*}" && update-ca-certificates || true'

ENV TZ=Europe/Zurich
RUN apk add --no-cache --virtual .img-tz tzdata;\
    cp /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone;\
    apk del .img-tz;\
    echo /usr/share/zoneinfo/$TZ | cut -d'/' -f-5 | xargs mkdir -p;\
    cp /etc/localtime /usr/share/zoneinfo/$TZ

#ENV MIMALLOC_SHOW_STATS=1

ENV DO_NOT_TRACK=1
ENV NODE_ENV=production

# ENV NODE_TLS_REJECT_UNAUTHORIZED=0
# ENV BUN_CONFIG_MAX_HTTP_REQUESTS=64
# ENV BUN_CONFIG_VERBOSE_FETCH=curl
# ENV BUN_CONFIG_VERBOSE_FETCH=true

RUN sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

COPY Taskfile.yml .
RUN task compile:musl:init
RUN rm -rf Taskfile.yml out 
